version: "3"

services:
  database:
    container_name: world-db
    image: mariadb:jammy
    ports:
      - 3306:3306
    volumes:
      - world-db:/var/lib/mysql
    environment:
      - MYSQL_USER=example-user
      - MYSQL_PASSWORD=user-password
      - MYSQL_ROOT_PASSWORD=root-secret-password
      - MYSQL_DATABASE=world-db

  phpmyadmin:
    depends_on:
      - database
    container_name: phpmyadmin
    image: phpmyadmin:5.2.1-apache
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=database
      - PMA_USER=root
      - PMA_PASSWORD=root-secret-password

volumes:
  world-db: